generator: admingenerator.generator.doctrine
params:
    model: UserBundle\Entity\User
    namespace_prefix: Admin
    concurrency_lock: ~
    bundle_name: BlogBundle
    pk_requirement: ~
    fields: ~
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: List for BlogBundle
            display: [username,email,roles]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params:
            display: [username]
        filename: ~
        filetype: ~
    new:
        params:
            title: New object for BlogBundle
            display: [username]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object \"%object%\"|{ %object%: User.username }|"
            display: [username]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: User.username }|"
            display: [username]
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
