admin:
    resource: "@AdminBlogBundle/Resources/config/routing/routing.yml"
    prefix:   /admin

dashboard:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /admin

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /admin/group

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"
     prefix: /admin

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"